// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2WTtS4quVgjDpWxePxJCTZ
// Component: otNIW0nTl04H
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: gZvr4N5QjhJc/component
import Button from "../../Button"; // plasmic-import: ZwkS9sai7CnT/component
import Price from "../../Price"; // plasmic-import: w5QKnQMfLd3u/component
import Select from "../../Select"; // plasmic-import: E0lnUZd6nv31/component
import Select__Option from "../../Select__Option"; // plasmic-import: P1gRSW4t3bSi/component
import Separator from "../../Separator"; // plasmic-import: v1uK0ZI0cWKk/component
import ProductCard from "../../ProductCard"; // plasmic-import: gO6ZyA-ndrIU/component
import Footer from "../../Footer"; // plasmic-import: CPf8NLxOGzsK/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: QS8WGXlJZeEM/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: 2WTtS4quVgjDpWxePxJCTZ/projectcss
import * as sty from "./PlasmicItem.module.css"; // plasmic-import: otNIW0nTl04H/css
import HomeIcon from "./icons/PlasmicIcon__Home"; // plasmic-import: nn8LRTzvWsWP/icon
import LikeIcon from "./icons/PlasmicIcon__Like"; // plasmic-import: uCQyIVLoYRbP/icon
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: 6dsV1XVlsxXG/icon
import shoe20AHJoLeRsbfU from "./images/shoe20.png"; // plasmic-import: A_hJoLERsbfU/picture
import shoe28Pc8MURhlgnym from "./images/shoe28.png"; // plasmic-import: pc8mURhlgnym/picture
import shoe23Hh8R8XnLtzFd from "./images/shoe23.png"; // plasmic-import: hh8R8XnLTZFd/picture
import shoe26MptfqtOt1Cn8 from "./images/shoe26.png"; // plasmic-import: mptfqtOT1CN8/picture
import shoe27E3KcnVpMeoQ4 from "./images/shoe27.png"; // plasmic-import: E3KcnVPMeoQ4/picture
import shoe24PHhVuaF6JxwI from "./images/shoe24.png"; // plasmic-import: pHHVuaF6JxwI/picture
import shoe25WYn2AgAkVdGh from "./images/shoe25.png"; // plasmic-import: WYn2AgAkVdGH/picture
import shoe21TFbvK9Ss9Wy4 from "./images/shoe21.png"; // plasmic-import: TFbvK9ss9WY4/picture
import shoe225Ialgmv74CgF from "./images/shoe22.png"; // plasmic-import: 5ialgmv74cgF/picture

export const PlasmicItem__VariantProps = new Array();

export const PlasmicItem__ArgProps = new Array("container42");

function PlasmicItem__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
          />

          <section className={classNames(defaultcss.all, sty.section__eLhyf)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container432"}
              data-plasmic-override={overrides.container432}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container432)}
            >
              <Button
                startIcon={
                  <HomeIcon
                    className={classNames(defaultcss.all, sty.svg__gToHu)}
                    role={"img"}
                  />
                }
              >
                {"Mens"}
              </Button>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__rLIiK
                )}
              >
                {"/"}
              </div>

              <Button
                startIcon={
                  <HomeIcon
                    className={classNames(defaultcss.all, sty.svg__g0Bdw)}
                    role={"img"}
                  />
                }
              >
                {"Shoes"}
              </Button>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__kbyKv
                )}
              >
                {"/"}
              </div>

              <Button
                startIcon={
                  <HomeIcon
                    className={classNames(defaultcss.all, sty.svg__pRga)}
                    role={"img"}
                  />
                }
              >
                {"Running"}
              </Button>
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__uxBnY)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox___2X26E)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__kVcLr)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__vNuU)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={{
                    src: shoe20AHJoLeRsbfU,
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__vD3Kr)}
                >
                  <div
                    className={classNames(defaultcss.all, sty.freeBox__sAqNt)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__wvEj)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: shoe28Pc8MURhlgnym,
                        fullWidth: 2000,
                        fullHeight: 2000,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox__pIykQ)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__rJrim)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: shoe23Hh8R8XnLtzFd,
                        fullWidth: 450,
                        fullHeight: 450,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__jeeUu)}
                >
                  <div
                    className={classNames(defaultcss.all, sty.freeBox__rC26I)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__r4X19)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: shoe26MptfqtOt1Cn8,
                        fullWidth: 2000,
                        fullHeight: 2000,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox___6Wtzu)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__ph9QC)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: shoe27E3KcnVpMeoQ4,
                        fullWidth: 2000,
                        fullHeight: 2000,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__c1ImH)}
                >
                  <div
                    className={classNames(defaultcss.all, sty.freeBox___70Ew)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__p8KFg)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: shoe24PHhVuaF6JxwI,
                        fullWidth: 2000,
                        fullHeight: 2000,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox__jBo6D)}
                  >
                    {true ? (
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__cMp59)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: shoe25WYn2AgAkVdGh,
                          fullWidth: 2000,
                          fullHeight: 2000,
                          aspectRatio: undefined
                        }}
                      />
                    ) : null}
                  </div>
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__ugM74)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__tLRgt
                  )}
                >
                  {"Eternity NITRO Men's Running Shoes"}
                </div>

                <Price
                  data-plasmic-name={"price"}
                  data-plasmic-override={overrides.price}
                  className={classNames("__wab_instance", sty.price)}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__lZ8Sx)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__kKVpr)}
                    displayHeight={"64px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"64px"}
                    src={{
                      src: shoe21TFbvK9Ss9Wy4,
                      fullWidth: 450,
                      fullHeight: 450,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__oXZu5)}
                    displayHeight={"64px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"64px"}
                    src={{
                      src: shoe225Ialgmv74CgF,
                      fullWidth: 450,
                      fullHeight: 450,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__oXzuF)}
                    displayHeight={"64px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"64px"}
                    src={{
                      src: shoe23Hh8R8XnLtzFd,
                      fullWidth: 450,
                      fullHeight: 450,
                      aspectRatio: undefined
                    }}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__nTN)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ivpCk
                    )}
                  >
                    {"Size"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__nRuMm)}
                  >
                    <Button colors={"lightGrayOutline"}>{"7"}</Button>

                    <Button colors={"lightGrayOutline"}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text___0Q3Xl
                        )}
                      >
                        {"7.5"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline"}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__iubd2
                        )}
                      >
                        {"8"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline"}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__v18Bb
                        )}
                      >
                        {"8.5"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline"}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text___6VPnp
                        )}
                      >
                        {"9"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline"}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__wMhIh
                        )}
                      >
                        {"9.5"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline"}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__xuXbY
                        )}
                      >
                        {"10"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline"}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__igmJh
                        )}
                      >
                        {"10.5"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline"}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__eeNoQ
                        )}
                      >
                        {"11"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline"}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__ff0Vh
                        )}
                      >
                        {"11.5"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline"}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__wozSu
                        )}
                      >
                        {"12"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline"}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__tNqu0
                        )}
                      >
                        {"13"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline"}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__ohJ
                        )}
                      >
                        {"14"}
                      </div>
                    </Button>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__ebXZr)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__nWzxf)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__vFqop
                      )}
                    >
                      {"Quantity"}
                    </div>

                    <Select
                      data-plasmic-name={"quantity"}
                      data-plasmic-override={overrides.quantity}
                      className={classNames("__wab_instance", sty.quantity)}
                      defaultValue={"1"}
                    >
                      <Select__Option
                        className={classNames(
                          "__wab_instance",
                          sty.option__nh73A
                        )}
                        value={"1"}
                      >
                        {"1"}
                      </Select__Option>

                      <Select__Option
                        className={classNames(
                          "__wab_instance",
                          sty.option__dPbtv
                        )}
                        value={"2"}
                      >
                        {"2"}
                      </Select__Option>

                      <Select__Option
                        className={classNames(
                          "__wab_instance",
                          sty.option__tqkxp
                        )}
                        value={"3"}
                      >
                        {"3"}
                      </Select__Option>

                      <Select__Option
                        className={classNames(
                          "__wab_instance",
                          sty.option__moKaj
                        )}
                        value={"4"}
                      >
                        {"4"}
                      </Select__Option>

                      <Select__Option
                        className={classNames(
                          "__wab_instance",
                          sty.option___8Qndl
                        )}
                        value={"5"}
                      >
                        {"5"}
                      </Select__Option>
                    </Select>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__dQp5B)}
                  >
                    <Button
                      data-plasmic-name={"likeButton"}
                      data-plasmic-override={overrides.likeButton}
                      colors={"lightGrayOutline"}
                      iconOnly={"iconOnly"}
                      size={"large"}
                      startIcon={
                        <LikeIcon
                          className={classNames(defaultcss.all, sty.svg__cAkJ2)}
                          role={"img"}
                        />
                      }
                    />

                    <Button
                      data-plasmic-name={"addToCartButton"}
                      data-plasmic-override={overrides.addToCartButton}
                      colors={"black"}
                      link={"/cart"}
                      rounded={"rounded"}
                      size={"large"}
                    >
                      {"Add to cart"}
                    </Button>
                  </p.Stack>
                </p.Stack>

                <Separator
                  className={classNames("__wab_instance", sty.separator__j0HVj)}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__wJluf)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__lg5T
                    )}
                  >
                    {"Description"}
                  </div>

                  <div
                    data-plasmic-name={"description"}
                    data-plasmic-override={overrides.description}
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.description
                    )}
                  >
                    {
                      "Let Eternity NITRO be your guide. The engineered mesh upper integrates the runGUIDE tech, designed to hug your midfoot for an effortless ride. For the midsole, NITRO foam provides superior cushioning, combining with other tech elements to give you support: a TPU heel piece for proprioception, reflectivity, and a durable rubber PUMAGRIP for all-surface traction. You lead the way, Eternity NITRO will keep you in line."
                    }
                  </div>
                </p.Stack>

                <Separator
                  className={classNames("__wab_instance", sty.separator__pj8Su)}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__qFyF7)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__z3C6N
                    )}
                  >
                    {"Details"}
                  </div>

                  <div
                    data-plasmic-name={"details"}
                    data-plasmic-override={overrides.details}
                    className={classNames(defaultcss.all, sty.details)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__ps1Bm
                      )}
                    >
                      {"Adaptive fit with midfoot wrap for secure lockdown"}
                    </div>

                    <Separator
                      className={classNames(
                        "__wab_instance",
                        sty.separator__r2DaN
                      )}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__m5Hw9
                      )}
                    >
                      {"Engineered mesh upper for support"}
                    </div>

                    <Separator
                      className={classNames(
                        "__wab_instance",
                        sty.separator__yc2QJ
                      )}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__e9SwZ
                      )}
                    >
                      {"Full lace closure for snug fit"}
                    </div>

                    <Separator
                      className={classNames(
                        "__wab_instance",
                        sty.separator__s4460
                      )}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__om42J
                      )}
                    >
                      {
                        "NITRO FOAM midsole for lightweight, responsive cushioning"
                      }
                    </div>
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__lojOe)}>
            <div
              data-plasmic-name={"container42"}
              data-plasmic-override={overrides.container42}
              className={classNames(defaultcss.all, sty.container42)}
            >
              {p.renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(defaultcss.all, sty.freeBox__pmd1H)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__mGbps
                      )}
                    >
                      {"You may also like"}
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__sOZng
                      )}
                      colors={"link"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(
                            defaultcss.all,
                            sty.svg___5SNlz
                          )}
                          role={"img"}
                        />
                      }
                      showEndIcon={"showEndIcon"}
                    >
                      {"See more"}
                    </Button>
                  </div>
                ),

                value: args.container42
              })}
            </div>

            <div
              data-plasmic-name={"container5"}
              data-plasmic-override={overrides.container5}
              className={classNames(defaultcss.all, sty.container5)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__c894)}
              >
                <ProductCard
                  img={{
                    src: shoe14HcmXw5VBu3V,
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"http://google.com"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__qqAcd
                    )}
                  >
                    {"ADIDAS ULTRABOOST DNA X LEGO® PLATES SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__fwNd1
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__zcJhA
                  )}
                  img={{
                    src: shoe8BQgKm4AaLied,
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__lutxH
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__v5FG
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___4Qgkr
                  )}
                  img={{
                    src: shoe16XIwZj8LtIvG5,
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__vX6Q
                    )}
                  >
                    {"Club C 85 Vintage Men's Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__pwjVh
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__x0QtT
                  )}
                  img={{
                    src: shoe177TtyqGNnjc2,
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__xEIb
                    )}
                  >
                    {"Nike Air Max Genome"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__xY6G
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___5Dsl6
                  )}
                  img={{
                    src: shoe18SaIe7QuFh9K0,
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__vygBi
                    )}
                  >
                    {"ULTRABOOST DNA 1.0 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___3B8Gg
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__oz8Qf
                  )}
                  link={"/item"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />
              </p.Stack>
            </div>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "container432",
    "price",
    "quantity",
    "likeButton",
    "addToCartButton",
    "description",
    "details",
    "container42",
    "container5",
    "footer"
  ],

  navBar: ["navBar"],
  container432: ["container432"],
  price: ["price"],
  quantity: ["quantity"],
  likeButton: ["likeButton"],
  addToCartButton: ["addToCartButton"],
  description: ["description"],
  details: ["details"],
  container42: ["container42"],
  container5: ["container5"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicItem__ArgProps,
      internalVariantPropNames: PlasmicItem__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicItem__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicItem";
  } else {
    func.displayName = `PlasmicItem.${nodeName}`;
  }
  return func;
}

export const PlasmicItem = Object.assign(
  // Top-level PlasmicItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    container432: makeNodeComponent("container432"),
    price: makeNodeComponent("price"),
    quantity: makeNodeComponent("quantity"),
    likeButton: makeNodeComponent("likeButton"),
    addToCartButton: makeNodeComponent("addToCartButton"),
    description: makeNodeComponent("description"),
    details: makeNodeComponent("details"),
    container42: makeNodeComponent("container42"),
    container5: makeNodeComponent("container5"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicItem
    internalVariantProps: PlasmicItem__VariantProps,
    internalArgProps: PlasmicItem__ArgProps
  }
);

export default PlasmicItem;
/* prettier-ignore-end */
