// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2WTtS4quVgjDpWxePxJCTZ
// Component: 3kBY-XuPVzE8
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: gZvr4N5QjhJc/component
import Button from "../../Button"; // plasmic-import: ZwkS9sai7CnT/component
import ProductCard from "../../ProductCard"; // plasmic-import: gO6ZyA-ndrIU/component
import Footer from "../../Footer"; // plasmic-import: CPf8NLxOGzsK/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: QS8WGXlJZeEM/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: 2WTtS4quVgjDpWxePxJCTZ/projectcss
import * as sty from "./PlasmicCategory.module.css"; // plasmic-import: 3kBY-XuPVzE8/css
import FilledCircleIcon from "./icons/PlasmicIcon__FilledCircle"; // plasmic-import: 3yKKrpGqlUEd/icon
import EmptyCircleIcon from "./icons/PlasmicIcon__EmptyCircle"; // plasmic-import: 8hPcTPDGfnAB/icon

export const PlasmicCategory__VariantProps = new Array();

export const PlasmicCategory__ArgProps = new Array();

function PlasmicCategory__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
            searchOpen={"searchOpen"}
          />

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(defaultcss.all, sty.section)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container6)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox___4WCv)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__sw2ZW)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___0G03Z
                    )}
                  >
                    {"Categories"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__v81Go)}
                    states={"active"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__ttjb4
                      )}
                    >
                      {"All"}
                    </div>
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__se5RS)}
                  >
                    {"New"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__jg4Aj)}
                  >
                    {"Womens"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button___6Jub)}
                  >
                    {"Mens"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__xo7L)}
                  >
                    {"Kids"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__aPoz)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__m0OS0
                      )}
                    >
                      {"On sale"}
                    </div>
                  </Button>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__zgg1Y)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__lKgxo
                    )}
                  >
                    {"Price"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__hzdv0)}
                  >
                    {"$0 - $50"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__gEzVx)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__tbqoM
                      )}
                    >
                      {"$51 - $99"}
                    </div>
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__pg7Cq)}
                  >
                    {"$101+"}
                  </Button>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__lsHYp)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__yjNk
                    )}
                  >
                    {"Colors"}
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox___3OoOg)}
                  >
                    <Button
                      iconOnly={"iconOnly"}
                      size={"narrow"}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__xXOnD)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__tbTXv
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly"}
                      size={"narrow"}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__unvPs)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__qqPvY
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly"}
                      size={"narrow"}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(
                            defaultcss.all,
                            sty.svg___1Xmpn
                          )}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__brmft
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly"}
                      size={"narrow"}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__x2I)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text___37Diz
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly"}
                      size={"narrow"}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__pOnLh)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text___4MhDx
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly"}
                      size={"narrow"}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__lwBP)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__xxHCk
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly"}
                      size={"narrow"}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__xdtzX)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__hNtDm
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly"}
                      size={"narrow"}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__kCjxn)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__oNmYu
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly"}
                      size={"narrow"}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__iYyAk)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__iy426
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly"}
                      size={"narrow"}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__i8453)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__slOb
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly"}
                      size={"narrow"}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(
                            defaultcss.all,
                            sty.svg___7TjSm
                          )}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text___9UouD
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly"}
                      size={"narrow"}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__ojN3Q)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__xAvNh
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly"}
                      size={"narrow"}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(
                            defaultcss.all,
                            sty.svg___1G71N
                          )}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__jsQEk
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly"}
                      size={"narrow"}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__iZyV)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__oAtmz
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly"}
                      size={"narrow"}
                      startIcon={
                        <EmptyCircleIcon
                          className={classNames(
                            defaultcss.all,
                            sty.svg___8Xz2Q
                          )}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text___1H2V
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox___0A9K3)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__qKceG
                    )}
                  >
                    {"Brands"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__ac7Lp)}
                  >
                    {"Adidas"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__v5Sx1)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__iVmig
                      )}
                    >
                      {"Asics"}
                    </div>
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__z5Ijc)}
                  >
                    {"Crocs"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__txKrw)}
                  >
                    {"Fila"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__lvVl)}
                  >
                    {"Nike"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__vb7Gt)}
                  >
                    {"Puma"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__fFj51)}
                  >
                    {"Reebok"}
                  </Button>
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__jSaf)}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__bIa8Q
                  )}
                  img={{
                    src: shoe2O12ZaIkjxR3,
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__pthrE
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38 Limited Edition"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__njiR
                    )}
                  >
                    {"Women's Running Shoe"}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__a5SPc
                  )}
                  img={{
                    src: shoe3XpQ6WEEqHYb,
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__fa8KF
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__jbb5Z
                    )}
                  >
                    {"Continue the NMD legacy in these adidas NMD_R1 Shoes."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___25Ha1
                  )}
                  img={{
                    src: shoe4Su5Gz5C0ZgBp,
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___7ZdWu
                    )}
                  >
                    {"Question Low Men's Basketball Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__pbRSc
                    )}
                  >
                    {"Lace up fierce baller style."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__pmuwK
                  )}
                  img={{
                    src: shoe5ASp0KtjT65M,
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__k6TOe
                    )}
                  >
                    {"Cali Women's Sneakers"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__uHzvX
                    )}
                  >
                    {"A sport style turned street classic."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__yKbZ
                  )}
                  img={{
                    src: shoe6GsnfUc7KQq3O,
                    fullWidth: 320,
                    fullHeight: 320,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__jeKr9
                    )}
                  >
                    {"MAGIC SPEED"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___83Snx
                    )}
                  >
                    {"mMade for racing or regular training runs."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__mKr3L
                  )}
                  img={{
                    src: shoe7Wk2I9I0TgKH,
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__oyXHt
                    )}
                  >
                    {"Pride Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__u9My7
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___2KIm8
                  )}
                  img={{
                    src: shoe8BQgKm4AaLied,
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___2Cy7W
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__zuVjz
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___9Bnjr
                  )}
                  img={{
                    src: shoe9GeuyNPhGaJd,
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__yagaj
                    )}
                  >
                    {"GEL-Nimbus 22 Retro Tokyo"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ifqh
                    )}
                  >
                    {"Enjoy comfort with each stride."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___5JdjO
                  )}
                  img={{
                    src: shoe10Xaa3Nw09Y6Dm,
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__vk57A
                    )}
                  >
                    {"A Bug's World Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__si1Xz
                    )}
                  >
                    {"Allover glow-in-the-dark bug prints."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__lnFvq
                  )}
                  img={{
                    src: shoe11GkzeDv8HzzIf,
                    fullWidth: 766,
                    fullHeight: 766,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__n7GXr
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__cLhRx
                    )}
                  >
                    {
                      "Effortlessly step up your look than a pop of animal print."
                    }
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__smGzm
                  )}
                  img={{
                    src: shoe12YVkyBsD8Laz1,
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__dvgfN
                    )}
                  >
                    {"Suede Teams Little Kids' Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ww6OX
                    )}
                  >
                    {"Worn by the icons of every generation."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__pn4Hi
                  )}
                  img={{
                    src: shoe13Ckq7Iqxr1GgK,
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__jSRa
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__cjCcf
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__jfAs2
                  )}
                  img={{
                    src: shoe14HcmXw5VBu3V,
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__yxiah
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__gHrNk
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__zuIY
                  )}
                  img={{
                    src: shoe15ZebqEmCmDgmu,
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___5Xowa
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___1SfVk
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__d6Kk
                  )}
                  img={{
                    src: shoe16XIwZj8LtIvG5,
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__xtuWg
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___5KbYf
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__iK5Ia
                  )}
                  img={{
                    src: shoe177TtyqGNnjc2,
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__rMZM
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__spbR
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>
              </p.Stack>
            </p.Stack>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "navBar", "section", "container6", "footer"],
  navBar: ["navBar"],
  section: ["section", "container6"],
  container6: ["container6"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCategory__ArgProps,
      internalVariantPropNames: PlasmicCategory__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicCategory__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCategory";
  } else {
    func.displayName = `PlasmicCategory.${nodeName}`;
  }
  return func;
}

export const PlasmicCategory = Object.assign(
  // Top-level PlasmicCategory renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    section: makeNodeComponent("section"),
    container6: makeNodeComponent("container6"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicCategory
    internalVariantProps: PlasmicCategory__VariantProps,
    internalArgProps: PlasmicCategory__ArgProps
  }
);

export default PlasmicCategory;
/* prettier-ignore-end */
